version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: "blog_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  backend:
    build: ./
    container_name: backend
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres:5432/blog_db'
    depends_on:
      - postgres
    ports:
      - "8080:8080"